# docker-compose.yml

version: '3.8'

services:
  # 1. Dịch vụ PostgreSQL Database (db)
  db:
    image: postgres:16-alpine
    container_name: pharmacy_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pharmacy_db
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 

  # 2. Dịch vụ FastAPI Application (app)
  app:
    build: . 
    container_name: pharmacy_fastapi_app
  
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 
    volumes:
     
      - .:/usr/src/app 
    ports:
      - "8000:8000"
    env_file: 
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
